### ISSUE TITLE
Config file should be `persist_properties.conf` with the underscore

### ISSUE THREAD

**Issue by automatata** [d87/mpv-persist-properties#1]
As subject, the filename mentioned in the `README.md` is incorrect.

Despite the script name is `persist-properties.lua` with the hyphen,
`mp.get_script_name()` will format the filename with underscores and return `'persist_properties'`.
Such value will be used as the `identifier`, when omitted, in
`options.read_options(table [, identifier [, on_update]])`
which is the case in the script.

Fixing the above reveals another issue when a non-number property is saved and later loaded.
`[persist_properties] Lua error: ...\user\AppData\Roaming/mpv/scripts/persist-properties.lua:65: bad argument #2 to 'set_property_number' (number expected, got boolean)`

I believe the following line in the `onInitialLoad` function,
`mp.set_property_number(name, value)`
should be
`mp.set_property_native(name, value)`
(or with `set_property` and ensuring `value` to be a string?)
Although I'm new to the mpv scripting API and haven't read all the document to be totally sure yet.

By the way thanks for the useful script.

**Comment by d87** [comment]
Thanks for pointing that out, fixed
