### ISSUE TITLE
Script is not working on Winows with portable_config

### ISSUE THREAD

**Issue by randombyt** [d87/mpv-persist-properties#2]
Hi, The script does not work in Win 8.1 with portable_config. I have placed script, persist-properties.lua,  in /portable_config/scripts. The conf file, persist_properties.conf, is placed in portable_config/script-opts. 

So far tried to name both script and conf file similarly, placing the script file in /script and removing volume=## from mpv.conf. None of which worked. I am using latest windows build of mpv by shinchiro.

**Comment by d87** [comment]
Fixed, the problem was with missing path for the save file, now it'll save in the portable_config root. Otherwise file naming is fine, it's a weird mpv "convention" that scripts files are kebab case, but conf files are underscore case

**Comment by randombyt** [comment]
Working as intended now, thanks a lot! closing the issue.
