### ISSUE TITLE
Trying to save 'time in ms vs not' and 'time left vs total time'

### ISSUE THREAD

**Issue by AstudilloMarillo** [d87/mpv-persist-properties#9]
I believe these properties are called 'timems' and 'timetotal' respectively, but they're not persisted when I put them in the persist-properties.lua. Can't find what else they're supposed to be called. Can't these properties be saved? Right now they keep getting reset upon restart when I toggle them.

**Comment by po5** [comment]
https://github.com/po5/celebi/issues/5
